#!/usr/bin/env ruby

require 'bundler/setup'
require 'hal9k'

module Heroku
  class Cli < Hal9k::Command
    # Default to cascading scope (non local)
    flag :application, :a, local: false

    def call
      puts '-> heroku'
    end

    class Status < Hal9k::Command
      mount Cli

      def call
        puts '-> heroku status'
      end
    end

    class Config < Hal9k::Command
      mount Cli

      # Maybe allow one command to handle mutiple paths
      # All the flags would need to be the same
      # register :get,   with: self
      # register :set,   with: self
      # register :unset, with: self

      def call
        puts '-> heroku config'
      end

      class Get < Hal9k::Command
        mount Config
        # register :get, with: Config

        def call
          puts '-> heroku config get'
        end
      end

      class Set < Hal9k::Command
        mount Config
        # register :set, with: Config

        def call
          puts '-> heroku config set'
        end
      end

      class Unset < Hal9k::Command
        mount Config
        # register :unset, with: Config

        def call
          puts '-> heroku config unset'
        end
      end
    end
  end
end

Heroku::Cli.start
