#!/usr/bin/env ruby

require 'bundler/setup'
require 'hal9k'

# Maybe support a dsl after the non-dsl setup is working
# Hal9k.cli do
#   flag :application, :a
#   run { puts '-> heroku' }

#   command :status do
#     run { puts '-> heroku status' }
#   end

#   command :config do
#     command :get do
#       run(variable) { puts "-> heroku config get #{variable}" }
#     end

#     command :set do
#       run(*variables) { puts "-> heroku config set #{variables.join(' ')}" }
#     end
#   end
# end

module Heroku
  class Cli < Hal9k::Command
    # Default to cascading scope (non local)
    flag :application, :a

    def call
      puts '-> heroku'
    end

    class Status < Hal9k::Command
      mount_to Cli

      def call
        puts "Showing status of #{flags[:application]}"
      end
    end

    class Config < Hal9k::Command
      mount_to Cli

      # Maybe allow one command to handle mutiple paths
      # All the flags would need to be the same
      # register :get,   with: self
      # register :set,   with: self
      # register :unset, with: self

      def call
        puts "Getting config of #{flags[:application]}"
      end

      class Get < Hal9k::Command
        mount_to Config
        # register :get, with: Config

        argument :variable

        def call
          puts "Getting #{arguments.first.upcase} from application #{flags[:application]}"
        end
      end

      class Set < Hal9k::Command
        mount_to Config
        # register :set, with: Config

        arguments :variables

        def call
          puts "Setting #{arguments.inspect} on #{flags[:application]}"
        end
      end

      class Unset < Hal9k::Command
        mount_to Config
        # register :unset, with: Config

        arguments :variables

        def call
          puts "Unsetting #{arguments.inspect} on #{flags[:application]}"
        end
      end
    end
  end
end

Heroku::Cli.start
