#!/usr/bin/env ruby

require 'bundler/setup'
require 'hal9k'

module Math
  class Cli < Hal9k::Command
    class Add < Hal9k::Command
      mount_to Cli

      arguments :integers, type: Hal9k::Integer

      def call
        puts arguments.reduce(:+)
      end
    end

    class AddOnlyTwo < Hal9k::Command
      mount_to Cli

      argument :x, type: Hal9k::Integer
      argument :y, type: Hal9k::Integer

      def call
        puts arguments.first + arguments.last
        # TODO: support the following
        # puts argument.first + arguments.last
        # puts arguments[:x] + arguments[:y]
      end
    end

    class LabelAdd < Hal9k::Command
      mount_to Cli

      argument :label, type: Hal9k::String
      argument :rest, type: Hal9k::Integer, count: :*

      def call
        puts "#{arguments.first}#{arguments[1..-1].reduce(:+)}"
      end
    end
  end
end

Math::Cli.start
